/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class View_producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form View_producto
     */
    public View_producto() {
        initComponents();
    }

    public JButton getBtguardarPR() {
        return btguardarPR;
    }

    public void setBtguardarPR(JButton btguardarPR) {
        this.btguardarPR = btguardarPR;
    }

    public JButton getBuscarPR() {
        return buscarPR;
    }

    public void setBuscarPR(JButton buscarPR) {
        this.buscarPR = buscarPR;
    }

    public JTextField getCantidadPrtxt() {
        return cantidadPrtxt;
    }

    public void setCantidadPrtxt(JTextField cantidadPrtxt) {
        this.cantidadPrtxt = cantidadPrtxt;
    }

    public JButton getEditarPR() {
        return editarPR;
    }

    public void setEditarPR(JButton editarPR) {
        this.editarPR = editarPR;
    }

    public JButton getEliminarPR() {
        return eliminarPR;
    }

    public void setEliminarPR(JButton eliminarPR) {
        this.eliminarPR = eliminarPR;
    }

    public JButton getLimpiar1PR() {
        return limpiar1PR;
    }

    public void setLimpiar1PR(JButton limpiar1PR) {
        this.limpiar1PR = limpiar1PR;
    }

    public JButton getLimpiarbuscadorPR() {
        return limpiarbuscadorPR;
    }

    public void setLimpiarbuscadorPR(JButton limpiarbuscadorPR) {
        this.limpiarbuscadorPR = limpiarbuscadorPR;
    }

    public JCheckBox getMostrarPR() {
        return mostrarPR;
    }

    public void setMostrarPR(JCheckBox mostrarPR) {
        this.mostrarPR = mostrarPR;
    }

    public JTextField getNombrePRTXT() {
        return nombrePRTXT;
    }

    public void setNombrePRTXT(JTextField nombrePRTXT) {
        this.nombrePRTXT = nombrePRTXT;
    }

    public JTextField getPrecioPRtxr() {
        return precioPRtxr;
    }

    public void setPrecioPRtxr(JTextField precioPRtxr) {
        this.precioPRtxr = precioPRtxr;
    }

    public JTable getTablaproducto() {
        return tablaproducto;
    }

    public void setTablaproducto(JTable tablaproducto) {
        this.tablaproducto = tablaproducto;
    }

    public JTextField getTxtbuscarPR() {
        return txtbuscarPR;
    }

    public void setTxtbuscarPR(JTextField txtbuscarPR) {
        this.txtbuscarPR = txtbuscarPR;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtbuscarPR = new javax.swing.JTextField();
        nombrePRTXT = new javax.swing.JTextField();
        precioPRtxr = new javax.swing.JTextField();
        cantidadPrtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        limpiarbuscadorPR = new javax.swing.JButton();
        editarPR = new javax.swing.JButton();
        eliminarPR = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btguardarPR = new javax.swing.JButton();
        buscarPR = new javax.swing.JButton();
        mostrarPR = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproducto = new javax.swing.JTable();
        limpiar1PR = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("PRODUCTOS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Criterio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel4.setText("NOMBRE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setText("PRECIO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setText("CANTIDAD");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel1.add(txtbuscarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 230, 30));
        jPanel1.add(nombrePRTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, 30));
        jPanel1.add(precioPRtxr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 30));
        jPanel1.add(cantidadPrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 30));

        jButton1.setText("Cancelar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 110, 40));

        limpiarbuscadorPR.setText("limpiar");
        jPanel1.add(limpiarbuscadorPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 70, 40));

        editarPR.setText("editar");
        jPanel1.add(editarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 50, 40));

        eliminarPR.setText("eliminar");
        jPanel1.add(eliminarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 50, 40));

        jLabel8.setText("Administracion de Productos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel9.setText("lista de Productos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 20));

        jLabel10.setText("Opciones de busqueda");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        btguardarPR.setText("guardar");
        jPanel1.add(btguardarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 50, 40));
        jPanel1.add(buscarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 100, 40));

        mostrarPR.setText("Mostrar todo");
        mostrarPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPRActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        jLabel11.setText("Busqueda de Productos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 20));

        tablaproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaproducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 620, 230));

        limpiar1PR.setText("limpiar");
        jPanel1.add(limpiar1PR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 50, 40));
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 50, 40));
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarPRActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btguardarPR;
    private javax.swing.JButton buscarPR;
    private javax.swing.JTextField cantidadPrtxt;
    private javax.swing.JButton editarPR;
    private javax.swing.JButton eliminarPR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar1PR;
    private javax.swing.JButton limpiarbuscadorPR;
    private javax.swing.JCheckBox mostrarPR;
    private javax.swing.JTextField nombrePRTXT;
    private javax.swing.JTextField precioPRtxr;
    private javax.swing.JTable tablaproducto;
    private javax.swing.JTextField txtbuscarPR;
    // End of variables declaration//GEN-END:variables
}
